repo_url: https://github.com/ELZAI/memora/
site_author: ELZAI

site_name: Memora
site_description: Memora is an agent that aims to replicate the human memory for every personalized AI.
site_url: https://elzai.github.io/memora/

theme:
  name: material
  favicon: pictures/favicon.png
  logo: pictures/white_logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: black
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Inter
    code: JetBrains Mono

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.path
    - navigation.tracking
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips

plugins:
  - search
  - exclude-search:
      exclude:
        - api/prompts/*
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            show_root_heading: true
            show_category_heading: true
            heading_level: 2
            docstring_style: google
            show_signature_annotations: true
            separate_signature: true
            show_symbol_type_heading: true
            docstring_section_style: spacy
            show_if_no_docstring: true
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

watch:
  - memora

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - def_list

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Advanced Usage: advanced_usage.md

  - API Reference:
    - Overview: api/index.md

    - Agent:
      - Memora: api/agent/memora.md

    - Graph Database:
      - BaseGraphDB: api/graph_db/base.md
      - Neo4j: api/graph_db/neo4j.md

    - Vector Database:
      - BaseVectorDB: api/vector_db/base.md
      - MemorySearchScope: api/vector_db/memory_search_scope.md
      - Qdrant: api/vector_db/qdrant.md

    - LLM Backend:
      - BaseBackendLLM: api/llm_backends/base.md
      - Azure OpenAI: api/llm_backends/azure_openai.md
      - Groq: api/llm_backends/groq.md
      - OpenAI: api/llm_backends/openai.md
      - Together: api/llm_backends/together.md

    - Schema:
      - Memory Extraction: api/schema/extraction.md
      - Memory Storage: api/schema/storage.md

    - Prompts:
      - Extraction: api/prompts/extraction.md
      - Search: api/prompts/search.md
      - Filter: api/prompts/filter.md

  - Change Log: changelog.md

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.elzai.com

    - icon: fontawesome/brands/github
      link: https://github.com/ELZAI/memora/
      
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/80737492/